// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saas.golf.domain;

import com.saas.golf.domain.GolferDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GolferDataOnDemand_Roo_Configurable {
    
    declare @type: GolferDataOnDemand: @Configurable;
    
}
