// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saas.golf.domain;

import com.saas.golf.domain.Account;
import com.saas.golf.domain.AccountDataOnDemand;
import com.saas.golf.domain.Golfer;
import com.saas.golf.domain.GolferDataOnDemand;
import com.saas.golf.repository.GolferRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GolferDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GolferDataOnDemand: @Component;
    
    private Random GolferDataOnDemand.rnd = new SecureRandom();
    
    private List<Golfer> GolferDataOnDemand.data;
    
    @Autowired
    private AccountDataOnDemand GolferDataOnDemand.accountDataOnDemand;
    
    @Autowired
    GolferRepository GolferDataOnDemand.golferRepository;
    
    public Golfer GolferDataOnDemand.getNewTransientGolfer(int index) {
        Golfer obj = new Golfer();
        setAccount(obj, index);
        setDateCreated(obj, index);
        return obj;
    }
    
    public void GolferDataOnDemand.setAccount(Golfer obj, int index) {
        Account account = accountDataOnDemand.getRandomAccount();
        obj.setAccount(account);
    }
    
    public void GolferDataOnDemand.setDateCreated(Golfer obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public Golfer GolferDataOnDemand.getSpecificGolfer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Golfer obj = data.get(index);
        BigInteger id = obj.getId();
        return golferRepository.findOne(id);
    }
    
    public Golfer GolferDataOnDemand.getRandomGolfer() {
        init();
        Golfer obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return golferRepository.findOne(id);
    }
    
    public boolean GolferDataOnDemand.modifyGolfer(Golfer obj) {
        return false;
    }
    
    public void GolferDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = golferRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Golfer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Golfer>();
        for (int i = 0; i < 10; i++) {
            Golfer obj = getNewTransientGolfer(i);
            try {
                golferRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
