// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saas.golf.domain;

import com.saas.golf.domain.Account;
import com.saas.golf.domain.AccountDataOnDemand;
import com.saas.golf.domain.GolfClub;
import com.saas.golf.domain.GolfClubDataOnDemand;
import com.saas.golf.domain.GolfCourse;
import com.saas.golf.domain.GolfCourseDataOnDemand;
import com.saas.golf.repository.GolfClubRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GolfClubDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GolfClubDataOnDemand: @Component;
    
    private Random GolfClubDataOnDemand.rnd = new SecureRandom();
    
    private List<GolfClub> GolfClubDataOnDemand.data;
    
    @Autowired
    private AccountDataOnDemand GolfClubDataOnDemand.accountDataOnDemand;
    
    @Autowired
    private GolfCourseDataOnDemand GolfClubDataOnDemand.golfCourseDataOnDemand;
    
    @Autowired
    GolfClubRepository GolfClubDataOnDemand.golfClubRepository;
    
    public GolfClub GolfClubDataOnDemand.getNewTransientGolfClub(int index) {
        GolfClub obj = new GolfClub();
        setAccount(obj, index);
        setDateCreated(obj, index);
        setGolfClubName(obj, index);
        setGolfCourse(obj, index);
        return obj;
    }
    
    public void GolfClubDataOnDemand.setAccount(GolfClub obj, int index) {
        Account account = accountDataOnDemand.getRandomAccount();
        obj.setAccount(account);
    }
    
    public void GolfClubDataOnDemand.setDateCreated(GolfClub obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void GolfClubDataOnDemand.setGolfClubName(GolfClub obj, int index) {
        String golfClubName = "golfClubName_" + index;
        if (golfClubName.length() > 50) {
            golfClubName = golfClubName.substring(0, 50);
        }
        obj.setGolfClubName(golfClubName);
    }
    
    public void GolfClubDataOnDemand.setGolfCourse(GolfClub obj, int index) {
        GolfCourse golfCourse = golfCourseDataOnDemand.getRandomGolfCourse();
        obj.setGolfCourse(golfCourse);
    }
    
    public GolfClub GolfClubDataOnDemand.getSpecificGolfClub(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GolfClub obj = data.get(index);
        BigInteger id = obj.getId();
        return golfClubRepository.findOne(id);
    }
    
    public GolfClub GolfClubDataOnDemand.getRandomGolfClub() {
        init();
        GolfClub obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return golfClubRepository.findOne(id);
    }
    
    public boolean GolfClubDataOnDemand.modifyGolfClub(GolfClub obj) {
        return false;
    }
    
    public void GolfClubDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = golfClubRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GolfClub' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GolfClub>();
        for (int i = 0; i < 10; i++) {
            GolfClub obj = getNewTransientGolfClub(i);
            try {
                golfClubRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
