// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saas.golf.domain;

import com.saas.golf.domain.Player;
import com.saas.golf.domain.PlayerDataOnDemand;
import com.saas.golf.domain.PlayerParticipant;
import com.saas.golf.domain.PlayerParticipantDataOnDemand;
import com.saas.golf.domain.ScoreCard;
import com.saas.golf.domain.ScoreCardDataOnDemand;
import com.saas.golf.repository.PlayerParticipantRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PlayerParticipantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlayerParticipantDataOnDemand: @Component;
    
    private Random PlayerParticipantDataOnDemand.rnd = new SecureRandom();
    
    private List<PlayerParticipant> PlayerParticipantDataOnDemand.data;
    
    @Autowired
    private PlayerDataOnDemand PlayerParticipantDataOnDemand.playerDataOnDemand;
    
    @Autowired
    private ScoreCardDataOnDemand PlayerParticipantDataOnDemand.scoreCardDataOnDemand;
    
    @Autowired
    PlayerParticipantRepository PlayerParticipantDataOnDemand.playerParticipantRepository;
    
    public PlayerParticipant PlayerParticipantDataOnDemand.getNewTransientPlayerParticipant(int index) {
        PlayerParticipant obj = new PlayerParticipant();
        setPlayer(obj, index);
        setScoreCard(obj, index);
        return obj;
    }
    
    public void PlayerParticipantDataOnDemand.setPlayer(PlayerParticipant obj, int index) {
        Player player = playerDataOnDemand.getRandomPlayer();
        obj.setPlayer(player);
    }
    
    public void PlayerParticipantDataOnDemand.setScoreCard(PlayerParticipant obj, int index) {
        ScoreCard scoreCard = scoreCardDataOnDemand.getRandomScoreCard();
        obj.setScoreCard(scoreCard);
    }
    
    public PlayerParticipant PlayerParticipantDataOnDemand.getSpecificPlayerParticipant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PlayerParticipant obj = data.get(index);
        BigInteger id = obj.getId();
        return playerParticipantRepository.findOne(id);
    }
    
    public PlayerParticipant PlayerParticipantDataOnDemand.getRandomPlayerParticipant() {
        init();
        PlayerParticipant obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return playerParticipantRepository.findOne(id);
    }
    
    public boolean PlayerParticipantDataOnDemand.modifyPlayerParticipant(PlayerParticipant obj) {
        return false;
    }
    
    public void PlayerParticipantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = playerParticipantRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PlayerParticipant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PlayerParticipant>();
        for (int i = 0; i < 10; i++) {
            PlayerParticipant obj = getNewTransientPlayerParticipant(i);
            try {
                playerParticipantRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
